#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 17 14:59:39 2019

@author: ben
"""
import os
import pickle

def name_file(file):
    '''
        Provides a non-conflicting filename based on the file name provided
        Args:
            file : file name 
    '''
    i = 0
    o_file = file
    while os.path.isfile(file):
        i += 1
        file = o_file + "-" + str(i)
    return file

def save(obj, file, force=False):
    if not force:
        file = name_file(file)
    pickle.dump(obj, file)
    
def load(file):
    return pickle.load(file)